version: "3"
services:
  mariadb:
    image: "bitnami/mariadb:10.3"
    environment:
      # - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - "./data/mariadb:/bitnami/mariadb"
    user: root
    restart: always
  phpbb:
    image: "bitnami/phpbb:3.3.0"
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PHPBB_DATABASE_USER=${MARIADB_USER}
      - PHPBB_DATABASE_PASSWORD=${MARIADB_PASSWORD}
      - PHPBB_DATABASE_NAME=${MARIADB_DATABASE}
    ports:
      - "${PHPBB_PORT}:80"
    volumes:
      - "./data/phpbb:/bitnami"
    depends_on:
      - mariadb
    restart: always
  phpmyadmin:
    image: "bitnami/phpmyadmin"
    environment:
      - PHPMYADMIN_ALLOW_NO_PASSWORD=false
      - PHPMYADMIN_ALLOW_ARBITRARY_SERVER=true
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mariadb
    volumes:
      - "./data/phpmyadmin:/bitnami"
    restart: always
