version: "3"
services:
  mariadb:
    image: "bitnami/mariadb:10.3"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_phpbb
      - MARIADB_PASSWORD=asdfasdf
      - MARIADB_DATABASE=bitnami_phpbb
    ports:
      - "3306:3306"
    volumes:
      - "mariadb_data:/bitnami"
  phpbb:
    image: "bitnami/phpbb:3.3.0"
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PHPBB_DATABASE_USER=bn_phpbb
      - PHPBB_DATABASE_PASSWORD=asdfasdf
      - PHPBB_DATABASE_NAME=bitnami_phpbb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "phpbb_data:/bitnami"
    depends_on:
      - mariadb
  phpmyadmin:
    image: "bitnami/phpmyadmin"
    environment:
      - PHPMYADMIN_ALLOW_NO_PASSWORD=false
      - PHPMYADMIN_ALLOW_ARBITRARY_SERVER=true
    ports:
      - "8080:80"
      - "4443:443"
    depends_on:
      - mariadb
    volumes:
      - "phpmyadmin_data:/bitnami"
volumes:
  mariadb_data:
  phpbb_data:
  phpmyadmin_data:
